#!/usr/bin/env bash
# legacy bootstrap-tarballs was split into three separate steps:
#
# - generate-pull-request-file
# - build-tarballs
# - bootstrap-mission-portal
#
# todo: remove this script when it is no longer called from anywhere
set -e
thisdir="$(dirname "$0")"
bash "$thisdir"/generate-pull-request-file
bash "$thisdir"/build-tarballs
bash "$thisdir"/bootstrap-mission-portal
