name: Continuous Integration

on: pull_request

jobs:
  inspect_event:
    runs-on: ubuntu-latest
    steps:
      - name: Inspect workflow event
        run: |
          echo ${{ fromJSON(github.event) }}
          echo ${{ github.event.organization }}
#  build_cfengine_hub_package:
#    uses: ./.github/workflows/build-using-buildscripts.yml
#    secrets: inherit
#
#  deployment_tests:
#    needs: build_cfengine_hub_package
#    uses: ./.github/workflows/deployment-tests.yml
#    secrets: inherit
